# Generated by Django 3.2.12 on 2022-09-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome ou Razão Social')),
                ('documento', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ')),
            ],
        ),
    ]
