# Generated by Django 4.1.1 on 2022-09-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Tag')),
                ('classe', models.CharField(choices=[('bg-primary', 'Primária'), ('bg-secondary', 'Secundária'), ('bg-success', 'Sucesso'), ('bg-info', 'Informativa'), ('bg-warning', 'Aviso'), ('bg-danger', 'Perigo'), ('bg-dark', 'Fundo Escuro'), ('bg-light', 'Fundo Claro')], max_length=255, verbose_name='Classe da Tag')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato 1'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato 3'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_rep',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF Rep Legal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=455, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_rep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Rep Legal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Número '),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto De Referência'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tags',
            field=models.ManyToManyField(related_name='clientes', to='formularios.tags'),
        ),
    ]
