# Generated by Django 4.1.1 on 2022-09-28 16:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_tags_cliente_bairro_cliente_cep_cliente_complemento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tag'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.CharField(default='teste', max_length=255, verbose_name='Última Alteração Por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número '),
        ),
    ]
