# Generated by Django 4.1.1 on 2022-09-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_alter_tags_options_cliente_created_cliente_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF ou CNPJ'),
        ),
    ]
