# Generated by Django 4.1.1 on 2022-09-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_alter_cliente_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('-modified',), 'verbose_name_plural': 'Clientes'},
        ),
    ]
