# Generated by Django 4.1.1 on 2022-10-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_alter_cliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='kanban',
            field=models.CharField(default='Iniciado', max_length=255, verbose_name='Kanban'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='classe',
            field=models.CharField(choices=[('bg-primary', 'Fundo Azul Forte'), ('bg-secondary', 'Fundo Cinza'), ('bg-success', 'Fundo Verde'), ('bg-info', 'Fundo Azul Claro'), ('bg-warning', 'Fundo Amarelo'), ('bg-danger', 'Fundo Vermelho')], max_length=255, verbose_name='Classe da Tag'),
        ),
    ]
