# Generated by Django 4.1.1 on 2022-10-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_cliente_kanban_alter_tags_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
    ]
