# Generated by Django 4.1.1 on 2022-10-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbans',
            options={'verbose_name_plural': 'Kanban'},
        ),
    ]
